# Write your MySQL query statement below
-- MY SOln
-- SELECT 
--     product_id, MIN(year) AS first_year, quantity, price
-- FROM
--     Sales
-- GROUP BY
--     product_id;

-- Inner Subquery:

-- SELECT 
--   product_id, MIN(year) AS year 
-- FROM 
--   Sales 
-- GROUP BY 
--   product_id;


-- The inner subquery is grouping the Sales table by product_id.
-- For each product_id, it's finding the minimum year, i.e., the first year a product was sold.
-- This subquery returns a list of product_ids along with the corresponding first year they were sold.

-- SELECT 
--     product_id, year AS first_year, quantity, price
-- FROM
--     Sales
-- WHERE
--     (product_id, year) IN (subquery);

-- The main query is selecting product_id, year, quantity, and price from the Sales table.
-- The WHERE clause is using a condition (product_id, year) IN (subquery). This means it's filtering the rows from the Sales table where the combination of product_id and year is present in the list generated by the subquery.
-- Essentially, this condition ensures that only the rows corresponding to the first year of sale for each product are returned.


SELECT 
    product_id, year AS first_year, quantity, price
FROM
    Sales
WHERE
    (product_id, year) IN (
        SELECT 
        product_id, MIN(year) AS year 
        FROM 
        Sales 
        GROUP BY 
        product_id
    );